<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PerfumeSeeder extends Seeder
{
    public function run()
    {
        DB::table('perfume')->insert([
            [
                'brand'          => 'CK',
                'name'           => 'CK Euphoria',
                'image'          => 'images/perfumes/CK_CK Euphoria_60.jpg',
                'price'          => 85.00,
                'rrp'            => 120.00,
                'rrp_rm'         => 550.00,
                'size'           => 60,
                'quality'        => 'Original',
                'year'           => '2005',
                'suit'           => 'Women',
                'main_accord'    => 'Amber, Floral, Fruity',
                'top_notes'      => 'Pomegranate, Persimmon, Green Notes',
                'middle_notes'   => 'Black Orchid, Lotus Blossom, Champaca',
                'base_notes'     => 'Mahogany, Amber, Violet, Cream',
                'history'        => 'Calvin Klein Euphoria is a luxurious fragrance that captures the feeling of pure euphoria.',
                'suit_season'    => 'Fall, Winter',
                'suit_time'      => 'Night',
                'ref_shop'       => '',
                'variation_id'   => 'CK-EUPH-60',
                'percent_summer' => 20,
                'percent_autumn' => 70,
                'percent_winter' => 80,
                'percent_day'    => 30,
                'percent_night'  => 85,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'brand'          => 'CK',
                'name'           => 'Euphoria',
                'image'          => 'images/perfumes/CK_Euphoria_60.jpg',
                'price'          => 78.00,
                'rrp'            => 110.00,
                'rrp_rm'         => 500.00,
                'size'           => 60,
                'quality'        => 'Original',
                'year'           => '2005',
                'suit'           => 'Women',
                'main_accord'    => 'Amber, Woody, Floral',
                'top_notes'      => 'Pomegranate, Persimmon',
                'middle_notes'   => 'Black Orchid, Lotus',
                'base_notes'     => 'Mahogany, Amber, Musk',
                'history'        => 'A classic Calvin Klein fragrance with rich amber undertones.',
                'suit_season'    => 'Fall, Winter',
                'suit_time'      => 'Night',
                'ref_shop'       => '',
                'variation_id'   => 'CK-EUPH2-60',
                'percent_summer' => 15,
                'percent_autumn' => 65,
                'percent_winter' => 75,
                'percent_day'    => 25,
                'percent_night'  => 80,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'brand'          => 'CN',
                'name'           => 'Coco Mademoiselle',
                'image'          => 'images/perfumes/CN_Coco Mademoiselle_30.jpg',
                'price'          => 120.00,
                'rrp'            => 165.00,
                'rrp_rm'         => 750.00,
                'size'           => 30,
                'quality'        => 'Original',
                'year'           => '2001',
                'suit'           => 'Women',
                'main_accord'    => 'Citrus, Floral, Woody',
                'top_notes'      => 'Orange, Mandarin, Bergamot',
                'middle_notes'   => 'Rose, Jasmine, Mimosa',
                'base_notes'     => 'Patchouli, Vetiver, Vanilla, White Musk',
                'history'        => 'Chanel Coco Mademoiselle is a fresh oriental fragrance for the irrepressible young woman.',
                'suit_season'    => 'Spring, Summer',
                'suit_time'      => 'Day',
                'ref_shop'       => '',
                'variation_id'   => 'CN-COCO-30',
                'percent_summer' => 75,
                'percent_autumn' => 50,
                'percent_winter' => 30,
                'percent_day'    => 85,
                'percent_night'  => 50,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'brand'          => 'DR',
                'name'           => 'Miss Dior',
                'image'          => 'images/perfumes/DR_Miss Dior_60.jpg',
                'price'          => 130.00,
                'rrp'            => 175.00,
                'rrp_rm'         => 800.00,
                'size'           => 60,
                'quality'        => 'Original',
                'year'           => '2012',
                'suit'           => 'Women',
                'main_accord'    => 'Floral, Chypre, Fresh',
                'top_notes'      => 'Mandarin, Blood Orange, Rose',
                'middle_notes'   => 'Grasse Rose, Turkish Rose, Peony',
                'base_notes'     => 'Patchouli, Musk, Sandalwood',
                'history'        => 'Miss Dior is a couture fragrance, a floral tribute to Dior\'s love for flowers.',
                'suit_season'    => 'Spring, Summer',
                'suit_time'      => 'Day',
                'ref_shop'       => '',
                'variation_id'   => 'DR-MISS-60',
                'percent_summer' => 80,
                'percent_autumn' => 40,
                'percent_winter' => 20,
                'percent_day'    => 90,
                'percent_night'  => 35,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'brand'          => 'WS',
                'name'           => 'Dementia',
                'image'          => 'images/perfumes/WS_Dementia_30.jpg',
                'price'          => 25.00,
                'rrp'            => 40.00,
                'rrp_rm'         => 180.00,
                'size'           => 30,
                'quality'        => 'Inspired',
                'year'           => '2022',
                'suit'           => 'Unisex',
                'main_accord'    => 'Woody, Aromatic, Fresh',
                'top_notes'      => 'Bergamot, Lemon, Lavender',
                'middle_notes'   => 'Geranium, Sage, Cedar',
                'base_notes'     => 'Sandalwood, Musk, Amber',
                'history'        => 'An affordable everyday scent with clean fresh notes.',
                'suit_season'    => 'All Season',
                'suit_time'      => 'Day',
                'ref_shop'       => '',
                'variation_id'   => 'WS-DEM-30',
                'percent_summer' => 60,
                'percent_autumn' => 50,
                'percent_winter' => 40,
                'percent_day'    => 80,
                'percent_night'  => 30,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'brand'          => 'WS',
                'name'           => 'Emily VS',
                'image'          => 'images/perfumes/WS_Emily VS_60.jpg',
                'price'          => 30.00,
                'rrp'            => 45.00,
                'rrp_rm'         => 200.00,
                'size'           => 60,
                'quality'        => 'Inspired',
                'year'           => '2022',
                'suit'           => 'Women',
                'main_accord'    => 'Floral, Sweet, Powdery',
                'top_notes'      => 'Pink Pepper, Raspberry',
                'middle_notes'   => 'Peony, Rose, Magnolia',
                'base_notes'     => 'Musk, Cashmeran, Vanilla',
                'history'        => 'A sweet floral fragrance inspired by elegance and femininity.',
                'suit_season'    => 'Spring, Summer',
                'suit_time'      => 'Day',
                'ref_shop'       => '',
                'variation_id'   => 'WS-EMILY-60',
                'percent_summer' => 70,
                'percent_autumn' => 45,
                'percent_winter' => 25,
                'percent_day'    => 85,
                'percent_night'  => 40,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'brand'          => 'YSL',
                'name'           => 'YSL Premium',
                'image'          => 'images/perfumes/YSL_YSL Premium_90.jpg',
                'price'          => 150.00,
                'rrp'            => 200.00,
                'rrp_rm'         => 900.00,
                'size'           => 90,
                'quality'        => 'Original',
                'year'           => '2019',
                'suit'           => 'Women',
                'main_accord'    => 'Floral, Oriental, Vanilla',
                'top_notes'      => 'Cranberry, Bergamot, Pink Pepper',
                'middle_notes'   => 'Peony, Orange Blossom, Jasmine',
                'base_notes'     => 'Vanilla, Cashmeran, Cedar, Patchouli',
                'history'        => 'A premium YSL fragrance with an opulent blend of florals and vanilla.',
                'suit_season'    => 'Fall, Winter',
                'suit_time'      => 'Night',
                'ref_shop'       => '',
                'variation_id'   => 'YSL-PREM-90',
                'percent_summer' => 25,
                'percent_autumn' => 75,
                'percent_winter' => 85,
                'percent_day'    => 35,
                'percent_night'  => 90,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'brand'          => 'YSL',
                'name'           => 'Sara',
                'image'          => 'images/perfumes/YSL_Sara_90.png',
                'price'          => 140.00,
                'rrp'            => 190.00,
                'rrp_rm'         => 850.00,
                'size'           => 90,
                'quality'        => 'Original',
                'year'           => '2020',
                'suit'           => 'Women',
                'main_accord'    => 'Floral, Musky, Powdery',
                'top_notes'      => 'Pear, Bergamot, Mandarin',
                'middle_notes'   => 'Iris, Rose, Jasmine',
                'base_notes'     => 'Musk, Cedar, Cashmere Wood',
                'history'        => 'An elegant and sophisticated fragrance with delicate floral notes.',
                'suit_season'    => 'Spring, Fall',
                'suit_time'      => 'Day, Night',
                'ref_shop'       => '',
                'variation_id'   => 'YSL-SARA-90',
                'percent_summer' => 45,
                'percent_autumn' => 70,
                'percent_winter' => 55,
                'percent_day'    => 60,
                'percent_night'  => 65,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
        ]);
    }
}
